-- MySQL Script generated by MySQL Workbench
-- 03/31/19 23:19:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET latin1 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`client` ;

CREATE TABLE IF NOT EXISTS `bank`.`client` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pnc` VARCHAR(45) NOT NULL,
  `idCard` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `pnc_UNIQUE` (`pnc` ASC),
  UNIQUE INDEX `idCard_UNIQUE` (`idCard` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bank`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`account` ;

CREATE TABLE IF NOT EXISTS `bank`.`account` (
  `id` INT(11) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `amountMoney` DOUBLE NOT NULL,
  `dateCreation` DATE NOT NULL,
  `clientId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_client_idx` (`clientId` ASC),
  CONSTRAINT `fk_account_client`
    FOREIGN KEY (`clientId`)
    REFERENCES `bank`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bank`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`employee` ;

CREATE TABLE IF NOT EXISTS `bank`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bank`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`transaction` ;

CREATE TABLE IF NOT EXISTS `bank`.`transaction` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateTransaction` DATE NOT NULL,
  `fromAccount` INT(11) NOT NULL,
  `toAccount` INT(11) NOT NULL,
  `amountMoneyTransferred` DOUBLE NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_account_idx` (`fromAccount` ASC),
  INDEX `fk_dest_account_idx` (`toAccount` ASC),
  CONSTRAINT `fk_dest_account`
    FOREIGN KEY (`toAccount`)
    REFERENCES `bank`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_src_account`
    FOREIGN KEY (`fromAccount`)
    REFERENCES `bank`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
